sudo: false
dist: trusty
language: python

python:
  - "3.6"

ache:
  pip: true
  apt: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gfortran-6
      - liblapack-dev

git:
  depth: 1
env:
  global:
    - MAKEFLAGS="-j 2"

before_script:
  

script:
  - cd src
  - rm -r -f ../bin/linux/
  - make clean
  - COMPILER=gcc6 CXX=g++-6 FC=gfortran-6 STATIC=no make install
  - cd ..
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy pandas matplotlib nose
  - #pip install --upgrade pip
  - #pip install -r requirements.travis.txt
  - #pip install https://github.com/modflowpy/pymake/zipball/master
  - #pip install --upgrade jupyter
  - #pip install scipy 
  - #pip install nbconvert
  - #pip install nose-timer
  - #pip install coveralls
  - #pip install git+https://github.com/modflowpy/flopy.git@develop
  - git clone --depth 1 --single-branch -b develop https://github.com/modflowpy/flopy.git
  - cd flopy
  - python setup.py install
  - cd ..
  - #pip install git+https://github.com/jtwhite79/pyemu.git@develop
  - git clone --depth 1 --single-branch -b develop https://github.com/jtwhite79/pyemu.git
  - cd pyemu
  - python setup.py install
  - cd ..
  - export PYTHONPATH=$PYTHONPATH:.
  - #cd benchmarks
  - export PATH="./test_bin/linux:../test_bin/linux:../../test_bin/linux:$PATH"
  - #nosetests -v -w ./benchmarks travis_tests.py 
  - nosetests -v -w ./benchmarks ci_prep.py
  - nosetests -v -w ./benchmarks ies_test.py opt_test.py


after_success:
  - chmod +x trigger-travis.sh
  - ./trigger-travis.sh jtwhite79 pestpp-opt_benchmarks $TRAVIS_ACCESS_TOKEN
notifications:
  email: true
